import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import usersRouter from "./users.js";
import shopsRouter from "./shops.js";
import toolsRouter from "./tools.js";
import rentalsRouter from "./rentals.js";
import paymentsRouter from "./payments.js";
import analyticsRouter from "./analytics.js";
import plansRouter from "./plans.js";
import smsRouter from "./sms.js";
import walletRouter from "./wallet.js";
import ratingsRouter from "./ratings.js";
import maintenanceRouter from "./maintenance.js";
import bookingsRouter from "./bookings.js";
import referralsRouter from "./referrals.js";
import pricingRouter from "./pricing.js";
import projectsRouter from "./projects.js";
import notificationsRouter from "./notifications.js";
import contractsRouter from "./contracts.js";
import documentsRouter from "./documents.js";
import loyaltyRouter from "./loyalty.js";
import promoCodesRouter from "./promo-codes.js";
import favoritesRouter from "./favorites.js";
import damageReportsRouter from "./damage-reports.js";
import workerTasksRouter from "./worker-tasks.js";
import suppliersRouter from "./suppliers.js";
import inAppNotificationsRouter from "./in-app-notifications.js";
import exportRouter from "./export.js";
import auditRouter from "./audit.js";
import gpsRouter from "./gps.js";
import branchesRouter from "./branches.js";
import chatRouter from "./chat.js";
import aiRecommendRouter from "./ai-recommend.js";
import paymentSettingsRouter from "./payment-settings.js";
import paymentWebhooksRouter from "./payment-webhooks.js";
import deliveryRouter from "./delivery.js";
import workerPerformanceRouter from "./worker-performance.js";
import platformRouter from "./platform.js";
import withdrawalsRouter from "./withdrawals.js";
import aiAdminRouter from "./ai-admin.js";
import insuranceRouter from "./insurance.js";
import workerPackagesRouter from "./worker-packages.js";
import calculatorRouter from "./calculator.js";
import b2bRouter from "./b2b.js";
import subscriptionsRouter from "./subscriptions.js";
import peerListingsRouter from "./peer-listings.js";
import passportRouter from "./passport.js";
import hardwareRouter from "./hardware.js";
import fundsRouter from "./funds.js";
import biometricPaymentRouter from "./biometric-payment.js";
import uploadRouter from "./upload.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/users", usersRouter);
router.use("/shops", shopsRouter);
router.use("/tools", toolsRouter);
router.use("/rentals", rentalsRouter);
router.use("/payments", paymentsRouter);
router.use("/analytics", analyticsRouter);
router.use("/plans", plansRouter);
router.use("/sms", smsRouter);
router.use("/wallet", walletRouter);
router.use("/ratings", ratingsRouter);
router.use("/maintenance", maintenanceRouter);
router.use("/bookings", bookingsRouter);
router.use("/referrals", referralsRouter);
router.use("/pricing", pricingRouter);
router.use("/projects", projectsRouter);
router.use("/notifications", notificationsRouter);
router.use("/contracts", contractsRouter);
router.use("/documents", documentsRouter);
router.use("/loyalty", loyaltyRouter);
router.use("/promo-codes", promoCodesRouter);
router.use("/favorites", favoritesRouter);
router.use("/damage-reports", damageReportsRouter);
router.use("/worker-tasks", workerTasksRouter);
router.use("/suppliers", suppliersRouter);
router.use("/in-app-notifications", inAppNotificationsRouter);
router.use("/export", exportRouter);
router.use("/audit", auditRouter);
router.use("/gps", gpsRouter);
router.use("/branches", branchesRouter);
router.use("/chat", chatRouter);
router.use("/ai", aiRecommendRouter);
router.use("/ai", aiAdminRouter);
router.use("/payment-settings", paymentSettingsRouter);
router.use("/pay", paymentWebhooksRouter);
router.use("/delivery", deliveryRouter);
router.use("/worker-performance", workerPerformanceRouter);
router.use("/platform", platformRouter);
router.use("/withdrawals", withdrawalsRouter);
router.use("/insurance", insuranceRouter);
router.use("/worker-packages", workerPackagesRouter);
router.use("/calculator", calculatorRouter);
router.use("/b2b", b2bRouter);
router.use("/subscriptions", subscriptionsRouter);
router.use("/peer-listings", peerListingsRouter);
router.use("/passport", passportRouter);
router.use("/hardware", hardwareRouter);
router.use("/funds", fundsRouter);
router.use("/biometric-payment", biometricPaymentRouter);
router.use("/upload", uploadRouter);

export default router;
