import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import usersRouter from "./users.js";
import shopsRouter from "./shops.js";
import toolsRouter from "./tools.js";
import rentalsRouter from "./rentals.js";
import paymentsRouter from "./payments.js";
import analyticsRouter from "./analytics.js";
import plansRouter from "./plans.js";
import smsRouter from "./sms.js";
import walletRouter from "./wallet.js";
import ratingsRouter from "./ratings.js";
import maintenanceRouter from "./maintenance.js";
import bookingsRouter from "./bookings.js";
import referralsRouter from "./referrals.js";
import pricingRouter from "./pricing.js";
import projectsRouter from "./projects.js";
import notificationsRouter from "./notifications.js";
import contractsRouter from "./contracts.js";
import documentsRouter from "./documents.js";
import loyaltyRouter from "./loyalty.js";
import promoCodesRouter from "./promo-codes.js";
import favoritesRouter from "./favorites.js";
import damageReportsRouter from "./damage-reports.js";
import workerTasksRouter from "./worker-tasks.js";
import suppliersRouter from "./suppliers.js";
import inAppNotificationsRouter from "./in-app-notifications.js";
import exportRouter from "./export.js";
import auditRouter from "./audit.js";
import gpsRouter from "./gps.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/users", usersRouter);
router.use("/shops", shopsRouter);
router.use("/tools", toolsRouter);
router.use("/rentals", rentalsRouter);
router.use("/payments", paymentsRouter);
router.use("/analytics", analyticsRouter);
router.use("/plans", plansRouter);
router.use("/sms", smsRouter);
router.use("/wallet", walletRouter);
router.use("/ratings", ratingsRouter);
router.use("/maintenance", maintenanceRouter);
router.use("/bookings", bookingsRouter);
router.use("/referrals", referralsRouter);
router.use("/pricing", pricingRouter);
router.use("/projects", projectsRouter);
router.use("/notifications", notificationsRouter);
router.use("/contracts", contractsRouter);
router.use("/documents", documentsRouter);
router.use("/loyalty", loyaltyRouter);
router.use("/promo-codes", promoCodesRouter);
router.use("/favorites", favoritesRouter);
router.use("/damage-reports", damageReportsRouter);
router.use("/worker-tasks", workerTasksRouter);
router.use("/suppliers", suppliersRouter);
router.use("/in-app-notifications", inAppNotificationsRouter);
router.use("/export", exportRouter);
router.use("/audit", auditRouter);
router.use("/gps", gpsRouter);

export default router;
